### ISSUE TITLE
Access is denied when running "whoami" command.

### ISSUE THREAD

**Issue by DrorDvash** [Leo4j/Invoke-Impersonation#1]
Seems to work great, but why `whoami` command doesn't work?

![image](https://github.com/Leo4j/Token-Impersonation/assets/8413651/426cf881-bdba-4581-84c6-7c535d5eeffe)

I know i can see the current user using `[System.Security.Principal.WindowsIdentity]::GetCurrent().Name`, but there are more limitations?

**Comment by Leo4j** [comment]
What process are you impersonating ? This usually happens when you impersonate system processes, like winlogon for example. Have you tried impersonating a user that is currently logged in your system ?

Below I'm impersonating the domain Administrator account first, then the winlogon process

![image](https://github.com/Leo4j/Token-Impersonation/assets/61951374/a04ee8ed-b1aa-42d5-acce-d62a4f38bec6)

**Comment by DrorDvash** [comment]
When trying to steal a user token, I get errors.
It works only when elevating to SYSTEM and then stealing for a user.
but the "access denied" still occurs.
![image](https://github.com/Leo4j/Token-Impersonation/assets/8413651/6f33b537-327b-4c17-acdd-47f0822f9494)

NOTE: john is not local admin.

**Comment by Leo4j** [comment]
could you try and steal john’s explorer or cmd process token and see if it works ?
The purpose of stealing a user’s token is to use its alternate credentials (impersonation) for network access, not to perform actions locally

**Comment by DrorDvash** [comment]
![image](https://github.com/Leo4j/Token-Impersonation/assets/8413651/efa06032-b1b3-40b5-89b8-b14136b1fe29)

With other tools I also need to elevate to `SYSTEM` and then steal `john` token. you manage to steal other user without SYSTEM?
john is a local user not a domain user.

**Comment by Leo4j** [comment]
Stealing a token for a local user would serve no purpose. You cannot use that token for local actions. The tool is meant to steal a domain user token, to then access remote network resources with the same level of access as the user impersonated. 
As a domain user, and from an elevated prompt (not system) try and steal the token of another domain user logged on the machine, preferably the explorer or cmd process

**Comment by Leo4j** [comment]
Closing as the error was caused by the user trying to steal a local user token
